absl-py==0.15.0
addict==2.4.0
albumentations==1.1.0
antlr4-python3-runtime==4.8
appdirs==1.4.4
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///tmp/build/80754af9/argon2-cffi-bindings_1644569684262/work
asttokens==2.0.5
asynctest==0.13.0
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
awscli==1.23.7
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4 @ file:///opt/conda/conda-bld/beautifulsoup4_1650462163268/work
black==21.4b2
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
botocore==1.25.7
cachetools==4.2.4
certifi==2021.10.8
cffi @ file:///opt/conda/conda-bld/cffi_1642701102775/work
charset-normalizer==2.0.7
click==7.1.2
cloudpickle==2.0.0
codecov==2.1.12
colorama==0.4.4
commonmark==0.9.1
configparser==5.0.2
coverage==6.0.2
cycler==0.11.0
Cython @ file:///tmp/build/80754af9/cython_1626256955500/work
debugpy @ file:///tmp/build/80754af9/debugpy_1637091796427/work
decorator @ file:///tmp/build/80754af9/decorator_1632776554403/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
detectron2 @ git+https://github.com/facebookresearch/detectron2.git@335b19830e4ea5c5a74a085a04ff4a2f1a1dbf71
diffimg==0.2.3
distlib==0.3.4
docker-pycreds==0.4.0
docutils==0.15.2
easydict==1.9
editdistance==0.6.0
einops==0.4.1
entrypoints @ file:///tmp/build/80754af9/entrypoints_1649926445639/work
executing==0.8.3
exrex==0.10.5
fastjsonschema @ file:///tmp/build/80754af9/python-fastjsonschema_1620414857593/work/dist
filelock==3.6.0
filterpy==1.4.5
fire==0.4.0
flake8==4.0.1
future==0.18.2
fvcore==0.1.5.post20211023
gitdb==4.0.9
GitPython==3.1.24
google-auth==2.3.2
google-auth-oauthlib==0.4.6
grpcio==1.41.1
huggingface-hub==0.4.0
hydra-core==1.1.1
icecream==2.1.2
idna==3.3
imageio==2.10.1
imgaug==0.4.0
importlib-resources==5.3.0
iniconfig==1.1.1
iopath==0.1.9
ipykernel @ file:///tmp/build/80754af9/ipykernel_1646982648551/work/dist/ipykernel-6.9.1-py3-none-any.whl
ipython @ file:///tmp/build/80754af9/ipython_1632141392005/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work
isort==5.9.3
jedi @ file:///tmp/build/80754af9/jedi_1611333125342/work
Jinja2 @ file:///opt/conda/conda-bld/jinja2_1647436528585/work
jmespath==1.0.0
joblib==1.1.0
jsonschema @ file:///tmp/build/80754af9/jsonschema_1650025949224/work
jupyter==1.0.0
jupyter-client @ file:///opt/conda/conda-bld/jupyter_client_1650622202839/work
jupyter-console @ file:///opt/conda/conda-bld/jupyter_console_1647002188872/work
jupyter-core @ file:///tmp/build/80754af9/jupyter_core_1646994441805/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
kiwisolver==1.3.2
kwarray==0.5.19
lanms-neo==1.0.2
llvmlite==0.37.0
lmdb==1.2.1
Markdown==3.3.4
MarkupSafe @ file:///tmp/build/80754af9/markupsafe_1621528148836/work
matplotlib==3.4.3
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186064646/work
mkl-service==2.4.0
mmcls @ file:///tmp/tmp0vg9i1p4/mmclassification
mmcv-full==1.5.0
-e git+https://github.com/open-mmlab/mmdetection.git@240d7a31c745578aa8c4df54c3074ce78b690c34#egg=mmdet
model-index==0.1.11
mypy-extensions==0.4.3
natsort==7.1.0
nbclient @ file:///tmp/build/80754af9/nbclient_1650308366712/work
nbconvert @ file:///opt/conda/conda-bld/nbconvert_1649751911790/work
nbformat @ file:///tmp/build/80754af9/nbformat_1649827057626/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1649847908682/work
networkx==2.6.3
nlpaug==1.1.10
nltk==3.6.5
notebook @ file:///opt/conda/conda-bld/notebook_1651734535442/work
numba==0.54.1
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1626271506491/work
oauthlib==3.1.1
oidv6==1.0.5
olefile @ file:///Users/ktietz/demo/mc3/conda-bld/olefile_1629805411829/work
omegaconf==2.1.1
opencv-contrib-python==4.4.0.46
opencv-python==4.1.2.30
opencv-python-headless==4.1.2.30
openmim==0.1.5
ordered-set==4.0.2
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.3.4
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parso @ file:///tmp/build/80754af9/parso_1617223946239/work
pathspec==0.9.0
pathtools==0.1.2
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.4.0
platformdirs==2.5.2
pluggy==1.0.0
portalocker @ file:///tmp/build/80754af9/portalocker_1617135545854/work
prettytable==3.3.0
progressbar2==4.0.0
prometheus-client @ file:///opt/conda/conda-bld/prometheus_client_1643788673601/work
promise==2.3
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
protobuf==3.19.1
psutil==5.8.0
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyclipper==1.3.0
pycocotools==2.0.2
pycodestyle==2.8.0
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydot==1.4.2
pyflakes==2.4.0
Pygments @ file:///tmp/build/80754af9/pygments_1629234116488/work
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1636110947380/work
pytest==6.2.5
pytest-cov==3.0.0
pytest-runner==5.3.1
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-utils==3.1.0
pytz==2021.3
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq @ file:///tmp/build/80754af9/pyzmq_1638436375034/work
qtconsole @ file:///opt/conda/conda-bld/qtconsole_1649078897110/work
QtPy @ file:///opt/conda/conda-bld/qtpy_1649073884068/work
qudida==0.0.4
rapidfuzz==1.8.2
regex==2021.10.23
requests==2.26.0
requests-oauthlib==1.3.0
rich==12.4.0
rsa==4.7.2
s3transfer==0.5.2
sacremoses==0.0.47
scikit-image==0.18.3
scikit-learn==0.22.2
scipy==1.7.1
seaborn==0.11.2
segno==1.4.1
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
sentry-sdk==1.4.3
Shapely==1.8.0
shortuuid==1.0.1
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1623709665295/work
smmap==5.0.0
soupsieve @ file:///tmp/build/80754af9/soupsieve_1636706018808/work
subprocess32==3.5.4
tabulate==0.8.9
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
termcolor==1.1.0
terminado @ file:///tmp/build/80754af9/terminado_1644322581811/work
terminaltables==3.1.0
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
thop==0.0.31.post2005241907
tifffile==2021.10.12
timm==0.4.5
tokenizers==0.10.3
toml==0.10.2
tomli==1.2.2
torch==1.10.0
torchaudio==0.10.0
torchcontrib==0.0.2
torchvision==0.11.1
tornado @ file:///tmp/build/80754af9/tornado_1606942300299/work
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
traitlets @ file:///tmp/build/80754af9/traitlets_1632522747050/work
transformers==4.15.0
typing_extensions==4.2.0
ubelt==0.10.1
urllib3==1.26.7
validators==0.18.2
virtualenv==20.14.1
Wand==0.6.6
wandb==0.12.6
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webcolors==1.11.1
webencodings==0.5.1
Werkzeug==2.0.2
widgetsnbextension @ file:///tmp/build/80754af9/widgetsnbextension_1645009353553/work
xdoctest==0.15.10
yacs==0.1.8
yapf==0.31.0
yaspin==2.1.0
zipp @ file:///opt/conda/conda-bld/zipp_1641824620731/work
